"""Create initial sports event schema

Revision ID: 9b313b49415c
Revises: 
Create Date: 2026-03-25 17:46:34.347521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b313b49415c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('_sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time_utc', sa.Time(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_sport_id', sa.Integer(), nullable=False),
    sa.Column('_competition_id', sa.Integer(), nullable=False),
    sa.Column('_stage_id', sa.Integer(), nullable=True),
    sa.Column('_venue_id', sa.Integer(), nullable=True),
    sa.Column('_home_team_id', sa.Integer(), nullable=True),
    sa.Column('_away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['_away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['_competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['_home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['_sport_id'], ['sports.id'], ),
    sa.ForeignKeyConstraint(['_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['_venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('competitions')
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_table('stages')
    op.drop_table('sports')
    # ### end Alembic commands ###
